# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mqLxIrCZJbD60o_en8_1BGj0Giwhf-2U
"""

n1=float(input("Introduce un numero: "))
n2=float(input("Introde un numero dos: "))
suma=n1+n2

print("La suma es: ",suma)